name: deploy production

on:
  push:
    tags:
      - 'v*'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      #Checkout the repository to the GitHub Actions runner at main branch 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      # Verify Tag
      - name: verify tag
        run: |
          echo $GITHUB_SHA
          git branch --contains $GITHUB_SHA
          git branch --contains $GITHUB_SHA | sed -e 's/^[ \t *]*//' | grep '^main$'
          git checkout $GITHUB_SHA
      # Use pnpm
      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.10.5
      # Use node in .nvmrc and cache dependencies
      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version-file: 'v2/.nvmrc'
          cache: pnpm
          cache-dependency-path: v2/pnpm-lock.yaml
      #Install
      - name: pnpm Install
        run:  cd ./v2 && pnpm install
      # Lint Code
      - name: pnpm Lint
        run: cd ./v2 && pnpm lint
      # Generate code from most recent GraphQL schema
      # - name: pnpm generate schema
      # run: cd ./v2 && pnpm codegen-generate
      # Build
      - name: build
        run: cd ./v2 && pnpm build
        env:
          VUE_APP_SENTRY_SECURITY_TOKEN: ${{ secrets.VUE_APP_SENTRY_SECURITY_TOKEN }}
          VUE_APP_SENTRY_SECURITY_DSN: ${{ secrets.VUE_APP_SENTRY_SECURITY_DSN }}
          VUE_APP_PUBLIC_URL: ${{ secrets.VUE_APP_PUBLIC_URL }}
          VUE_APP_HTTP_LINK: ${{ secrets.VUE_APP_HTTP_LINK }}
          VUE_APP_WS_CLIENT: ${{ secrets.VUE_APP_WS_CLIENT }}
          VUE_APP_OPENSEA_API: ${{ secrets.VUE_APP_OPENSEA_API }}
          VUE_APP_FORMSPREE_CONTACT : ${{secrets.VUE_APP_FORMSPREE_CONTACT}}
          VUE_APP_GA_ID: ${{secrets.VUE_APP_GA_ID}}
          VUE_APP_AFFILIATE: ${{secrets.VUE_APP_AFFILIATE}}

      # Deploy to S3        
      - name: Deploy to S3
        if: github.base_ref == ''
        env:
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET}}
          VIRUS_TOTAL_API_KEY: ${{secrets.VIRUS_TOTAL_API_KEY}}
          GITHUB_TOKEN: ${{secrets.MEW_BOT_API_KEY}}
        run: |
          cd ./v2
          pip install --user awscli
          aws s3 sync --delete --acl public-read dist/ s3://ethvm-front-end-builds/production
          aws s3 cp s3://ethvm-front-end-builds/production/index.html s3://ethvm-front-end-builds/production/index.html \
            --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate \
            --content-type text/html --acl public-read
          cd dist && zip -r ../ethVM-$GITHUB_SHA.zip * && cd ..
          VIRUS_TOTAL_URL=`curl -s -F "file=@ethVM-$GITHUB_SHA.zip" -F apikey=${VIRUS_TOTAL_API_KEY} https://www.virustotal.com/vtapi/v2/file/scan | jq --raw-output '.permalink'`
          curl -H "Authorization: token ${GITHUB_TOKEN}" -X POST \
            -d "{\"body\": \"Copy of this build can be found at <br/>https://www.ethvm.com<br/> \
                            Virus Total analysis <br/> \
                            $VIRUS_TOTAL_URL\"}" \
                            "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/comments"
      - name: deploy to sentry
        env:
          SENTRY_AUTH_TOKEN: ${{secrets.VUE_APP_SENTRY_SECURITY_TOKEN}}
          SENTRY_ORG: myetherwallet-inc
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          TAG=${{ github.ref_name }}
          RELEASE=${TAG//v/}
          sentry-cli releases new -p ethvm-eth-front-end $RELEASE
          sentry-cli releases -p ethvm-eth-front-end files $RELEASE upload-sourcemaps ./v2/dist/sourcemaps --url-prefix 'https://www.ethvm.com/sourcemaps' --rewrite --validate
          sentry-cli releases set-commits $RELEASE --auto
          sentry-cli releases finalize $RELEASE
      #Create Release
      - name: Create release
        env:
          GITHUB_TOKEN: ${{secrets.MEW_BOT_API_KEY}}
        run: |
          bash ./release.sh ${{ github.ref_name }} $GITHUB_TOKEN $GITHUB_REPOSITORY true
